// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6xFB4cgjPaRYs9ViOFDmpANdI4qaPEu8',
    appId: '1:533315736129:web:5b62acc2f92150c6386cc0',
    messagingSenderId: '533315736129',
    projectId: 'mumma-tailor-hub',
    authDomain: 'mumma-tailor-hub.firebaseapp.com',
    storageBucket: 'mumma-tailor-hub.firebasestorage.app',
    measurementId: 'G-9VJLJSQXYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxZICDe-bQdle7hvfSrMUvmEBJI-eX894',
    appId: '1:533315736129:android:626debdc310e912d386cc0',
    messagingSenderId: '533315736129',
    projectId: 'mumma-tailor-hub',
    storageBucket: 'mumma-tailor-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwKsEPRsiRE9aNFGLhR7d4rUMuCDnK0Y',
    appId: '1:533315736129:ios:252a9d6627ec70d2386cc0',
    messagingSenderId: '533315736129',
    projectId: 'mumma-tailor-hub',
    storageBucket: 'mumma-tailor-hub.firebasestorage.app',
    iosBundleId: 'com.example.mummasTailorHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwKsEPRsiRE9aNFGLhR7d4rUMuCDnK0Y',
    appId: '1:533315736129:ios:252a9d6627ec70d2386cc0',
    messagingSenderId: '533315736129',
    projectId: 'mumma-tailor-hub',
    storageBucket: 'mumma-tailor-hub.firebasestorage.app',
    iosBundleId: 'com.example.mummasTailorHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6xFB4cgjPaRYs9ViOFDmpANdI4qaPEu8',
    appId: '1:533315736129:web:384df184baecef3d386cc0',
    messagingSenderId: '533315736129',
    projectId: 'mumma-tailor-hub',
    authDomain: 'mumma-tailor-hub.firebaseapp.com',
    storageBucket: 'mumma-tailor-hub.firebasestorage.app',
    measurementId: 'G-0871S4LF4K',
  );
}
